repos:
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://github.com/pycqa/flake8
    rev: '3.9.2'
    hooks:
    - id: flake8
      additional_dependencies: [flake8-bugbear]
      args: ["--show-source"]
-   repo: local
    hooks:
    -   id: clang-format
        name: clang-format
        description: Format files with clang-format
        entry: clang-format
        language: system
        files: ^(src\/nle|include\/nle|win\/rl|sys\/unix\/nle).*\.(c|cc|cxx|cpp|cu|h|hpp|hxx|cuh|proto)$
    -   id: cmake-format
        name: cmake-format
        description: Format CMake files
        entry: cmake-format
        language: system
        files: \.cmake$|CMakeLists\.txt$
    -   id: isort
        name: isort (python)
        description: Sort python imports
        entry: isort
        language: system
        files: \.(py|pyi)$
